[
  {
    "enable": true,
    "alias": "常庆涛",
    "phone": "17629481314",
    "password": "hjbjwxhn.q521",
    "deviceType": "Xiaomi|Mi 10 Ultra|14",
    "deviceId": "d41d6cb9189e4c268be0bb5e8bf69b6369fc",
    "randomLocation": true,
    "address": "中国河南省安阳市文峰区中所屯社区交个朋友食品店",
    "longitude": "114.381607",
    "latitude": "36.04649",
    "pushKey": "015d112c409a4490ae1e5b610a68b8bd"
  }
]
